/* Structured fields shared by form, live preview and CSV import. */
(function(root){
 'use strict';
 const lines=s=>String(s||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
 function specs(s){const out={};for(const line of lines(s)){const i=line.indexOf(':');if(i<1)throw Error('Especificaciones: usá Campo: valor, una por línea.');out[line.slice(0,i).trim()]=line.slice(i+1).trim();}return out;}
 function spans(s){if(!s.trim()||/^(cerrado|fechado)$/i.test(s.trim()))return [];return s.split(',').map(part=>{const m=part.trim().match(/^((?:[01]\d|2[0-3]):[0-5]\d)\s*-\s*((?:[01]\d|2[0-3]):[0-5]\d)$/);if(!m||m[1]>=m[2])throw Error('Horario: usá HH:MM-HH:MM, separando turnos con coma.');return [m[1],m[2]];});}
 function csv(raw){
  raw=String(raw).replace(/^\uFEFF/,'');const first=raw.split(/\r?\n/)[0];const delimiter=first.includes(';')?';':',';
  const rows=[];let row=[],cell='',quoted=false;
  for(let i=0;i<raw.length;i++){const c=raw[i],n=raw[i+1];if(c==='"'){if(quoted&&n==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}
  if(quoted)throw Error('CSV inválido: hay comillas sin cerrar.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);
  if(rows.length<2)throw Error('El CSV no contiene productos.');const headers=rows.shift().map(s=>s.trim().toLowerCase());
  if(!headers.includes('tienda')||!headers.includes('nombre'))throw Error('El CSV necesita las columnas tienda y nombre.');
  return rows.map((row,i)=>{if(row.length!==headers.length)throw Error(`Fila ${i+2}: cantidad de columnas incorrecta.`);const p={};headers.forEach((h,j)=>{if(h)p[h]=row[j].trim();});if(!p.tienda||!p.nombre)throw Error(`Fila ${i+2}: faltan tienda o nombre.`);for(const k of ['precio_usd','precio_original_usd']){if(p[k]){p[k]=Number(p[k].replace(',','.'));if(!Number.isFinite(p[k])||p[k]<0)throw Error(`Fila ${i+2}: precio inválido.`);}}for(const k of ['activo','en_oferta'])if(k in p)p[k]=!['false','0','no','não','nao'].includes(p[k].toLowerCase());if(p.especificaciones){try{p.especificaciones=p.especificaciones.startsWith('{')?JSON.parse(p.especificaciones):specs(p.especificaciones);}catch{throw Error(`Fila ${i+2}: especificaciones inválidas.`);}}else if('especificaciones' in p)p.especificaciones={};return p;});
 }
 // Full Google Maps links carry the place pin (!3d…!4d…) or the map centre (@lat,lng).
 function coordinatesFromUrl(url){const raw=String(url||'');let decoded=raw;try{decoded=decodeURIComponent(raw);}catch{}const m=decoded.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/)||decoded.match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/)||decoded.match(/[?&](?:q|query|ll|destination)=(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(!m)return null;const lat=Number(m[1]),lng=Number(m[2]);return Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng}:null;}
 const model={specs,spans,csv,coordinatesFromUrl};root.RivFreeCatalogFields=model;if(typeof module!=='undefined')module.exports=model;
 if(typeof document==='undefined')return;
 const $=id=>document.getElementById(id),value=id=>$(id).value.trim(),set=(id,v)=>{$(id).value=v??'';};
 const add=(form,markup)=>{const block=document.createElement('div');block.className='subsection';block.innerHTML=markup;$(form).querySelector('.form-actions').before(block);};
 add('productForm',`<h3>Ficha pública del producto</h3><label><span>Marca</span><input id="productBrand" maxlength="120"></label><label><span>Descripción</span><textarea id="productDescription" rows="4" maxlength="6000"></textarea></label><label><span>Especificaciones · una por línea, Campo: valor</span><textarea id="productSpecs" rows="5" placeholder="Almacenamiento: 256 GB&#10;Pantalla: 6,3 pulgadas"></textarea></label>`);
 add('storeForm',`<h3>Perfil público y trayectoria</h3><label><span>Descripción en español</span><textarea id="storeDescriptionEs" rows="4" maxlength="6000"></textarea></label><label><span>Descrição em português</span><textarea id="storeDescriptionPt" rows="4" maxlength="6000"></textarea></label><label><span>Especialidades · separadas por coma</span><input id="storeSpecialties" placeholder="Perfumes, electrónica, bebidas"></label><h3>Horarios y estado abierto</h3><label><span>Zona horaria IANA</span><input id="storeTimezone" value="America/Montevideo"></label><label class="check"><input id="storeHoursKnown" type="checkbox"><span>Horarios confirmados (permite mostrar abierto/cerrado)</span></label><p class="form-help">Usá horarios de 24 horas. Si no conocés el horario, desmarcá la confirmación.</p><div class="grid2">${['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'].map((d,i)=>`<label><span>${d}</span><input id="storeDay${i}" placeholder="09:00-18:00"></label>`).join('')}</div><label><span>Excepciones · una por línea</span><textarea id="storeExceptions" rows="3" placeholder="2026-12-25: cerrado&#10;2026-12-24: 09:00-14:00"></textarea></label><h3>Google y ubicación</h3><p class="form-help">Datos ingresados manualmente. Completalos solo con información verificada; no se sincronizan automáticamente con Google.</p><div class="grid2"><label><span>Evaluación (0 a 5)</span><input id="storeRating" type="number" min="0" max="5" step="0.1"></label><label><span>Cantidad de evaluaciones</span><input id="storeReviewCount" type="number" min="0" step="1"></label></div><label><span>Enlace de Google Maps</span><input id="storeMaps" type="url"></label><h3>Ubicación en el mapa de tiendas</h3><p class="form-help">Pegá el enlace completo del local en Google Maps (el que aparece en la barra del navegador al abrirlo, con <code>@-30.89…,-55.53…</code>) y tocá <strong>Leer coordenadas</strong>, o escribí la latitud y la longitud. Sin coordenadas la tienda no aparece en el mapa.</p><div class="grid2"><label><span>Latitud</span><input id="storeLat" type="number" step="0.0000001" min="-90" max="90" placeholder="-30.8986"></label><label><span>Longitud</span><input id="storeLng" type="number" step="0.0000001" min="-180" max="180" placeholder="-55.5389"></label></div><button id="storeReadCoordinates" class="button" type="button">Leer coordenadas del enlace de Google Maps</button><p id="storeCoordinatesHint" class="form-help" role="status"></p><label><span>Fuente de información</span><input id="storeInfoSource" type="url"></label><label><span>Fecha de verificación</span><input id="storeVerified" type="date"></label><label><span>Fotos · URL | descripción | atribución, una por línea</span><textarea id="storePhotos" rows="4" placeholder="https://ejemplo.com/local.jpg | Fachada | Foto de la tienda"></textarea></label>`);
 function location(){const lat=value('storeLat'),lng=value('storeLng');if(lat===''&&lng==='')return null;const point={lat:Number(lat),lng:Number(lng)};if(!Number.isFinite(point.lat)||!Number.isFinite(point.lng)||Math.abs(point.lat)>90||Math.abs(point.lng)>180)throw Error('Ubicación: completá latitud (-90 a 90) y longitud (-180 a 180), o dejá ambas vacías.');return point;}
 const readCoordinates=()=>{const hint=$('storeCoordinatesHint'),point=model.coordinatesFromUrl(value('storeMaps'));if(!point){hint.textContent=/maps\.app\.goo\.gl|goo\.gl\/maps/.test(value('storeMaps'))?'Los enlaces cortos (maps.app.goo.gl) no incluyen coordenadas: abrilo en el navegador y copiá la dirección completa de la barra.':'No encontramos coordenadas en ese enlace. Usá el enlace completo del local en Google Maps.';return;}set('storeLat',point.lat);set('storeLng',point.lng);hint.textContent='Coordenadas cargadas. Guardá la tienda para aplicarlas al mapa.';$('storeLat').dispatchEvent(new Event('input',{bubbles:true}));};
 $('storeReadCoordinates')?.addEventListener('click',readCoordinates);
 model.fillProduct=p=>{set('productBrand',p.marca);set('productDescription',p.descripcion);set('productSpecs',Object.entries(p.especificaciones||{}).map(([k,v])=>`${k}: ${v}`).join('\n'));};
 model.product=()=>({marca:value('productBrand'),descripcion:value('productDescription'),especificaciones:specs(value('productSpecs'))});
 model.fillStore=s=>{set('storeDescriptionEs',s.description?.es);set('storeDescriptionPt',s.description?.['pt-BR']);set('storeSpecialties',(s.specialties||[]).join(', '));set('storeTimezone',s.timezone||'America/Montevideo');$('storeHoursKnown').checked=!!s.weekly_hours;for(let i=0;i<7;i++)set('storeDay'+i,(s.weekly_hours?.[i]||[]).map(p=>p.join('-')).join(', '));set('storeExceptions',Object.entries(s.hours_exceptions||{}).map(([k,v])=>`${k}: ${v.length?v.map(p=>p.join('-')).join(', '):'cerrado'}`).join('\n'));set('storeRating',s.google?.rating);set('storeReviewCount',s.google?.count);set('storeMaps',s.google?.url);set('storeLat',s.ubicacion?.lat);set('storeLng',s.ubicacion?.lng);set('storeCoordinatesHint','');set('storeInfoSource',s.source);set('storeVerified',s.verified_at?.slice(0,10));set('storePhotos',(s.photos||[]).map(p=>[p.url,p.caption||'',p.attribution||''].join(' | ')).join('\n'));};
 model.store=()=>{try{new Intl.DateTimeFormat('es',{timeZone:value('storeTimezone')||'America/Montevideo'});}catch{throw Error('Zona horaria inválida. Ejemplo: America/Montevideo');}const exceptions={};for(const line of lines(value('storeExceptions'))){const match=line.match(/^(\d{4}-\d{2}-\d{2}):\s*(.*)$/);if(!match)throw Error('Excepciones: usá AAAA-MM-DD: HH:MM-HH:MM o cerrado.');exceptions[match[1]]=spans(match[2]);}return {description:{es:value('storeDescriptionEs'),'pt-BR':value('storeDescriptionPt')},specialties:value('storeSpecialties').split(',').map(s=>s.trim()).filter(Boolean),timezone:value('storeTimezone')||'America/Montevideo',weekly_hours:$('storeHoursKnown').checked?Object.fromEntries(Array.from({length:7},(_,i)=>[i,spans(value('storeDay'+i))])):null,hours_exceptions:exceptions,google:{rating:value('storeRating')===''?null:Number(value('storeRating')),count:value('storeReviewCount')===''?null:Number(value('storeReviewCount')),url:value('storeMaps')},ubicacion:location(),photos:lines(value('storePhotos')).map(line=>{const [url,caption='',attribution='']=line.split('|').map(s=>s.trim());return {url,caption,attribution};}),source:value('storeInfoSource'),verified_at:value('storeVerified')};};
})(typeof window==='undefined'?globalThis:window);
