(() => {
'use strict';
const E=window.RivFreeEditor;if(!E)return;
const $=id=>document.getElementById(id);
const clone=value=>JSON.parse(JSON.stringify(value||{}));
let workingConfig=null, workingHero=[], selectedCampaignId='', configDirty=false, heroDirty=false, ignoreStateOnce=false;
const sectionLabels={hero:'Carrusel principal',benefits:'Pasos 01 · 02 · 03',discover:'Por descubrir',popular:'Más consultados',catalog:'Catálogo y filtros'};
function setStudioDirty(type,value=true){if(type==='config')configDirty=value;if(type==='hero')heroDirty=value;E.setExternalDirty(configDirty||heroDirty);}
function stateEvent(event){
 const s=event.detail||{};if(s.mode!=='owner')return;
 $('campaignCount').textContent=Array.isArray(s.highlights?.hero)?s.highlights.hero.length:0;
 if(ignoreStateOnce){ignoreStateOnce=false;return;}
 if(!configDirty)workingConfig=clone(s.site_config||{});
 if(!heroDirty)workingHero=clone(s.highlights?.hero||[]);
 fillAll();
}
window.addEventListener('rivfree-editor-state',stateEvent);
function currentLangConfig(){return workingConfig||{};}
function ensureConfig(){
 if(workingConfig)return;
 const s=E.getState();workingConfig=clone(s.site_config||{});workingHero=clone(s.highlights?.hero||[]);
}
function val(id,v=''){const el=$(id);if(el)el.value=v??'';} function chk(id,v){const el=$(id);if(el)el.checked=!!v;}
function getColor(id,fallback){const v=$(id).value;return /^#[0-9a-f]{6}$/i.test(v)?v:fallback;}
function fillAppearance(){ensureConfig();const c=workingConfig,a=c.appearance||{},l=a.light||{},d=a.dark||{},b=c.branding||{};
 val('siteName',b.site_name||'RivFree');val('taglineEs',b.tagline_es||'');val('taglinePt',b.tagline_pt||'');val('siteFont',a.font||'system-modern');val('siteDensity',a.density||'comfortable');val('siteShadow',a.shadow||'soft');val('siteRadius',a.radius??12);$('radiusValue').textContent=`${a.radius??12}px`;
 for(const [prefix,p] of [['light',l],['dark',d]]){val(prefix+'Background',p.background|| (prefix==='light'?'#F1ECDE':'#101716'));val(prefix+'Surface',p.surface||(prefix==='light'?'#FFFFFF':'#17211F'));val(prefix+'Text',p.text||(prefix==='light'?'#1B1B1B':'#F2EFE7'));val(prefix+'Primary',p.primary||(prefix==='light'?'#123C39':'#194F4A'));val(prefix+'Accent',p.accent||(prefix==='light'?'#F06449':'#FF8068'));val(prefix+'Highlight',p.highlight||(prefix==='light'?'#BEEB72':'#C8F47E'));val(prefix+'BgImage',p.background_image||'');val(prefix+'Overlay',Math.round((Number(p.background_overlay)||0)*100));$(prefix+'OverlayValue').textContent=`${Math.round((Number(p.background_overlay)||0)*100)}%`;}
}
function readAppearance(){ensureConfig();workingConfig.branding={site_name:$('siteName').value.trim()||'RivFree',tagline_es:$('taglineEs').value.trim(),tagline_pt:$('taglinePt').value.trim()};workingConfig.appearance=workingConfig.appearance||{};Object.assign(workingConfig.appearance,{font:$('siteFont').value,density:$('siteDensity').value,shadow:$('siteShadow').value,radius:Number($('siteRadius').value)||0});for(const prefix of ['light','dark']){workingConfig.appearance[prefix]={background:getColor(prefix+'Background','#F1ECDE'),surface:getColor(prefix+'Surface','#FFFFFF'),text:getColor(prefix+'Text','#1B1B1B'),primary:getColor(prefix+'Primary','#123C39'),accent:getColor(prefix+'Accent','#F06449'),highlight:getColor(prefix+'Highlight','#BEEB72'),background_image:$(prefix+'BgImage').value.trim(),background_overlay:(Number($(prefix+'Overlay').value)||0)/100};}return workingConfig;}
function fillPage(){ensureConfig();const c=workingConfig,n=c.notice||{},seo=c.seo||{},f=c.footer||{};chk('noticeEnabled',n.enabled!==false);chk('noticeDismissible',n.dismissible!==false);val('noticeTitleEs',n.title_es);val('noticeTitlePt',n.title_pt);val('noticeTextEs',n.text_es);val('noticeTextPt',n.text_pt);val('seoTitleEs',seo.title_es);val('seoTitlePt',seo.title_pt);val('seoDescriptionEs',seo.description_es);val('seoDescriptionPt',seo.description_pt);val('seoSocialImage',seo.social_image||'social-card.png');val('footerTitleEs',f.title_es);val('footerTitlePt',f.title_pt);val('footerTextEs',f.text_es);val('footerTextPt',f.text_pt);chk('footerPrivacy',f.show_privacy!==false);renderSectionOrder();}
function readPage(){ensureConfig();workingConfig.notice={enabled:$('noticeEnabled').checked,dismissible:$('noticeDismissible').checked,title_es:$('noticeTitleEs').value.trim(),title_pt:$('noticeTitlePt').value.trim(),text_es:$('noticeTextEs').value.trim(),text_pt:$('noticeTextPt').value.trim()};workingConfig.seo={title_es:$('seoTitleEs').value.trim(),title_pt:$('seoTitlePt').value.trim(),description_es:$('seoDescriptionEs').value.trim(),description_pt:$('seoDescriptionPt').value.trim(),social_image:$('seoSocialImage').value.trim()||'social-card.png'};workingConfig.footer={title_es:$('footerTitleEs').value.trim(),title_pt:$('footerTitlePt').value.trim(),text_es:$('footerTextEs').value.trim(),text_pt:$('footerTextPt').value.trim(),show_privacy:$('footerPrivacy').checked};return workingConfig;}
function renderSectionOrder(){ensureConfig();const hp=workingConfig.homepage=workingConfig.homepage||{order:Object.keys(sectionLabels),visible:{}};hp.order=Array.isArray(hp.order)?hp.order:Object.keys(sectionLabels);for(const k of Object.keys(sectionLabels))if(!hp.order.includes(k))hp.order.push(k);hp.visible=hp.visible||{};const root=$('sectionOrder');root.replaceChildren();hp.order.forEach((key,index)=>{const row=document.createElement('div');row.className='section-order-row';const toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=hp.visible[key]!==false;toggle.onchange=()=>{hp.visible[key]=toggle.checked;setStudioDirty('config');sendPreview();};const label=document.createElement('strong');label.textContent=sectionLabels[key]||key;const controls=document.createElement('div');for(const [symbol,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='mini-button';b.textContent=symbol;b.disabled=(delta<0&&index===0)||(delta>0&&index===hp.order.length-1);b.onclick=()=>{const target=index+delta;[hp.order[index],hp.order[target]]=[hp.order[target],hp.order[index]];setStudioDirty('config');renderSectionOrder();sendPreview();};controls.append(b);}row.append(toggle,label,controls);root.append(row);});}
function campaignDefaults(){return {id:'',poolGroup:'general',theme:'rose',layout:'split',enabled:true,sponsored:false,eyebrow:{es:'', 'pt-BR':''},title:{es:'Nuevo banner','pt-BR':'Novo banner'},description:{es:'','pt-BR':''},cta:{es:'Explorar','pt-BR':'Explorar'},category:'',href:'',image:'',starts_at:'',ends_at:''};}
function campaignById(id){return workingHero.find(c=>c.id===id);}
function renderCampaignList(){ensureConfig();$('campaignCount').textContent=workingHero.length;const root=$('campaignList');root.replaceChildren();workingHero.forEach((c,index)=>{const row=document.createElement('div');row.className='list-item campaign-list-item'+(c.id===selectedCampaignId?' selected':'');row.dataset.id=c.id;const body=document.createElement('button');body.type='button';body.className='campaign-list-main';body.onclick=()=>editCampaign(c.id);const title=document.createElement('strong');title.textContent=c.title?.es||c.title?.['pt-BR']||c.id;const meta=document.createElement('small');meta.textContent=`${c.sponsored?'Patrocinado · ':''}${c.poolGroup||'general'} · ${c.enabled===false?'Inactivo':'Activo'}`;body.append(title,meta);const controls=document.createElement('span');controls.className='campaign-reorder';for(const [symbol,delta] of [['↑',-1],['↓',1]]){const b=document.createElement('button');b.type='button';b.className='mini-button';b.textContent=symbol;b.disabled=(delta<0&&index===0)||(delta>0&&index===workingHero.length-1);b.onclick=e=>{e.stopPropagation();const target=index+delta;[workingHero[index],workingHero[target]]=[workingHero[target],workingHero[index]];setStudioDirty('hero');renderCampaignList();sendPreview();};controls.append(b);}row.append(body,controls);root.append(row);});if(!workingHero.length){const d=document.createElement('div');d.className='empty-list';d.innerHTML='<strong>No hay banners.</strong><span>Creá el primero con “Nuevo banner”.</span>';root.append(d);}}
function toLocalDate(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return value.slice(0,16);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function editCampaign(id){ensureConfig();const c=campaignById(id)||campaignDefaults();selectedCampaignId=c.id||'';val('campaignId',c.id||'');val('campaignGroup',c.poolGroup||'general');val('campaignTheme',c.theme||'rose');val('campaignLayout',c.layout||'split');val('campaignSmart',c.smartType||'');chk('campaignEnabled',c.enabled!==false);chk('campaignSponsored',!!c.sponsored);val('campaignEyebrowEs',c.eyebrow?.es);val('campaignEyebrowPt',c.eyebrow?.['pt-BR']);val('campaignTitleEs',c.title?.es);val('campaignTitlePt',c.title?.['pt-BR']);val('campaignDescriptionEs',c.description?.es);val('campaignDescriptionPt',c.description?.['pt-BR']);val('campaignCtaEs',c.cta?.es);val('campaignCtaPt',c.cta?.['pt-BR']);val('campaignCategory',c.category);val('campaignHref',c.href);val('campaignStart',toLocalDate(c.starts_at));val('campaignEnd',toLocalDate(c.ends_at));val('campaignImage',c.image||c.images?.[0]?.src||'');$('campaignFormTitle').textContent=selectedCampaignId?(c.title?.es||'Editar banner'):'Nuevo banner';$('campaignSponsorBadge').textContent=c.sponsored?'Patrocinado':'Editorial';updateCampaignImagePreview();renderCampaignList();}
function slug(s){return String(s||'banner').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||`banner-${Date.now()}`;}
function campaignFromForm(){const existing=campaignById(selectedCampaignId)||{};const id=selectedCampaignId||`${slug($('campaignTitleEs').value)}-${Date.now().toString(36)}`;const out={...existing,id,poolGroup:$('campaignGroup').value,theme:$('campaignTheme').value,layout:$('campaignLayout').value,smartType:$('campaignSmart').value||undefined,enabled:$('campaignEnabled').checked,sponsored:$('campaignSponsored').checked,eyebrow:{es:$('campaignEyebrowEs').value.trim(),'pt-BR':$('campaignEyebrowPt').value.trim()},title:{es:$('campaignTitleEs').value.trim(),'pt-BR':$('campaignTitlePt').value.trim()},description:{es:$('campaignDescriptionEs').value.trim(),'pt-BR':$('campaignDescriptionPt').value.trim()},cta:{es:$('campaignCtaEs').value.trim(),'pt-BR':$('campaignCtaPt').value.trim()},category:$('campaignCategory').value.trim(),href:$('campaignHref').value.trim(),image:$('campaignImage').value.trim(),starts_at:$('campaignStart').value||undefined,ends_at:$('campaignEnd').value||undefined};delete out.images;return out;}
function updateCampaignImagePreview(){const root=$('campaignImagePreview'),src=$('campaignImage').value.trim();root.replaceChildren();if(!src){const span=document.createElement('span');span.textContent='Sin imagen';root.append(span);return;}const img=document.createElement('img');img.src=src;img.alt='';img.onerror=()=>{root.textContent='No se pudo cargar';};root.append(img);}
function fillCarouselSettings(){ensureConfig();const c=workingConfig.carousel||{};val('campaignVisibleCount',c.visible_count??5);chk('campaignAutoplay',c.autoplay!==false);val('campaignSeconds',c.autoplay_seconds??6);renderCampaignList();if(selectedCampaignId&&campaignById(selectedCampaignId))editCampaign(selectedCampaignId);else if(workingHero[0])editCampaign(workingHero[0].id);else editCampaign('');}
function readCarouselSettings(){ensureConfig();workingConfig.carousel={visible_count:Number($('campaignVisibleCount').value)||5,autoplay:$('campaignAutoplay').checked,autoplay_seconds:Number($('campaignSeconds').value)||6};return workingConfig;}
function previewFrames(){return [$('studioPreview')].filter(Boolean);}
function sendPreview(){ensureConfig();readAppearance();readPage();readCarouselSettings();for(const frame of previewFrames()){try{frame.contentWindow?.postMessage({type:'rivfree-studio-preview',config:workingConfig},location.origin);frame.contentWindow?.postMessage({type:'rivfree-studio-campaigns-preview',hero:workingHero},location.origin);}catch{}}}
async function uploadFile(inputId,targetId){const file=$(inputId).files[0];if(!file)return;const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('No se pudo leer la imagen'));r.readAsDataURL(file);});const out=await E.api('/api/manual/upload-image',{filename:file.name,data});$(targetId).value=out.path;setStudioDirty(targetId==='campaignImage'?'hero':'config');if(targetId==='campaignImage')updateCampaignImagePreview();sendPreview();E.notify('Imagen guardada en assets/manual/.');}
async function saveConfig(message){readAppearance();readPage();readCarouselSettings();try{const saved=await E.api('/api/manual/save-site-config',{config:workingConfig});ignoreStateOnce=true;E.applyState(saved);workingConfig=clone(saved.site_config||workingConfig);configDirty=false;E.setExternalDirty(heroDirty);E.notify(message);}catch(e){E.notify(e.message,true);}}
function fillAll(){if(E.getState().mode!=='owner')return;fillAppearance();fillPage();fillCarouselSettings();sendPreview();}

$('appearanceForm')?.addEventListener('input',e=>{readAppearance();if(e.target.id==='siteRadius')$('radiusValue').textContent=`${e.target.value}px`;if(e.target.id==='lightOverlay')$('lightOverlayValue').textContent=`${e.target.value}%`;if(e.target.id==='darkOverlay')$('darkOverlayValue').textContent=`${e.target.value}%`;setStudioDirty('config');sendPreview();});
$('pageForm')?.addEventListener('input',()=>{readPage();setStudioDirty('config');sendPreview();});
$('saveAppearance')?.addEventListener('click',()=>saveConfig('Diseño guardado.'));
$('savePageConfig')?.addEventListener('click',()=>saveConfig('Configuración de página guardada.'));
$('lightBgFile')?.addEventListener('change',()=>uploadFile('lightBgFile','lightBgImage').catch(e=>E.notify(e.message,true)));
$('darkBgFile')?.addEventListener('change',()=>uploadFile('darkBgFile','darkBgImage').catch(e=>E.notify(e.message,true)));
$('campaignImageFile')?.addEventListener('change',()=>uploadFile('campaignImageFile','campaignImage').catch(e=>E.notify(e.message,true)));
$('campaignImage')?.addEventListener('input',updateCampaignImagePreview);
$('campaignSponsored')?.addEventListener('change',()=>{$('campaignSponsorBadge').textContent=$('campaignSponsored').checked?'Patrocinado':'Editorial';});
$('campaignForm')?.addEventListener('submit',e=>{e.preventDefault();const c=campaignFromForm();if(!c.title.es&&!c.title['pt-BR'])return E.notify('Escribí un título para el banner.',true);const i=workingHero.findIndex(x=>x.id===c.id);if(i>=0)workingHero[i]=c;else workingHero.push(c);selectedCampaignId=c.id;setStudioDirty('hero');renderCampaignList();editCampaign(c.id);sendPreview();E.notify('Banner aplicado al borrador. Falta guardar el carrusel.');});
$('newCampaign')?.addEventListener('click',()=>{selectedCampaignId='';editCampaign('');$('campaignTitleEs').focus();});
$('duplicateCampaign')?.addEventListener('click',()=>{const base=campaignById(selectedCampaignId);if(!base)return;const copy=clone(base);copy.id=`${base.id}-copia-${Date.now().toString(36)}`;copy.title=copy.title||{};copy.title.es=`${copy.title.es||'Banner'} · copia`;workingHero.push(copy);selectedCampaignId=copy.id;setStudioDirty('hero');renderCampaignList();editCampaign(copy.id);sendPreview();});
$('deleteCampaign')?.addEventListener('click',()=>{if(!selectedCampaignId)return;if(!confirm('¿Eliminar este banner del borrador?'))return;workingHero=workingHero.filter(c=>c.id!==selectedCampaignId);selectedCampaignId=workingHero[0]?.id||'';setStudioDirty('hero');renderCampaignList();editCampaign(selectedCampaignId);sendPreview();});
for(const id of ['campaignVisibleCount','campaignAutoplay','campaignSeconds'])$(id)?.addEventListener('input',()=>{readCarouselSettings();setStudioDirty('config');sendPreview();});
$('saveCampaigns')?.addEventListener('click',async()=>{readCarouselSettings();try{if(configDirty){const savedConfig=await E.api('/api/manual/save-site-config',{config:workingConfig});ignoreStateOnce=true;E.applyState(savedConfig);workingConfig=clone(savedConfig.site_config||workingConfig);configDirty=false;}const saved=await E.api('/api/manual/save-highlights',{hero:workingHero});ignoreStateOnce=true;E.applyState(saved);workingHero=clone(saved.highlights?.hero||workingHero);heroDirty=false;E.setExternalDirty(false);fillCarouselSettings();E.notify('Carrusel guardado.');}catch(e){E.notify(e.message,true);}});
for(const b of document.querySelectorAll('.preview-size'))b.addEventListener('click',()=>{document.querySelectorAll('.preview-size').forEach(x=>x.classList.toggle('active',x===b));$('studioPreview').style.width=b.dataset.previewWidth;});
$('studioPreview')?.addEventListener('load',()=>setTimeout(sendPreview,500));

setTimeout(()=>{const s=E.getState();if(s?.site_config)stateEvent({detail:s});},50);
})();
