const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {JSDOM}=require('jsdom');
test('each page includes the supplied beacon once and no consent banner or Google tag',()=>{
 for(const file of ['index.html','privacy.html']){const dom=new JSDOM(fs.readFileSync(file,'utf8'));const d=dom.window.document;const scripts=d.querySelectorAll('script[data-cf-beacon]');assert.equal(scripts.length,1);assert.equal(JSON.parse(scripts[0].dataset.cfBeacon).token,'c7ffd1476a25414983f7c03faf7e0ace');assert.equal(scripts[0].src,'https://static.cloudflareinsights.com/beacon.min.js');assert.equal(scripts[0].type,'module');assert.equal(d.querySelector('#analyticsConsent'),null);assert.equal(d.querySelector('#privacySettings'),null);assert(![...d.scripts].some(s=>/googletagmanager|google-analytics/.test(s.src)));dom.window.close();}
});
test('cleanup removes analytics state and preserves favorites',()=>{
 const dom=new JSDOM('',{url:'https://rivfree.test/RivFree/',runScripts:'outside-only'});const w=dom.window;w.localStorage.setItem('rivfree-favorites','["saved"]');w.localStorage.setItem('rivfree-analytics-consent-v2','old');w.document.cookie='_ga=old;path=/';w.document.cookie='essential=keep;path=/';vm.runInContext(fs.readFileSync('analytics.js','utf8'),dom.getInternalVMContext());assert.equal(w.localStorage.getItem('rivfree-analytics-consent-v2'),null);assert.equal(w.localStorage.getItem('rivfree-favorites'),'["saved"]');assert(!w.document.cookie.includes('_ga='));assert(w.document.cookie.includes('essential=keep'));assert.equal(w.document.scripts.length,0);dom.window.close();
});
test('privacy language switching works without removed consent controls',()=>{
 const dom=new JSDOM(fs.readFileSync('privacy.html','utf8'),{url:'https://rivfree.test/privacy.html',runScripts:'outside-only'});dom.window.RIVFREE_PRIVACY={controllerName:'Test',contactEmail:'test@example.com'};vm.runInContext(fs.readFileSync('privacy.js','utf8'),dom.getInternalVMContext());const d=dom.window.document;d.getElementById('policyLanguage').value='es';d.getElementById('policyLanguage').dispatchEvent(new dom.window.Event('change'));assert.equal(d.documentElement.lang,'es');assert.equal(d.querySelector('[data-lang="es"]').hidden,false);assert(!d.querySelector('[data-lang="pt-BR"]').textContent.includes('Google Analytics'));dom.window.close();
});
