const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync('consent.js','utf8');
function setup(url='https://rivfree.test/project/',saved=null){
 const events={},storage=new Map(),els=[];if(saved)storage.set('rivfree-cookie-choice-v4',saved);
 class Element{constructor(tag){this.tagName=tag;this.children=[];els.push(this)}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}setAttribute(k,v){this[k]=v}}
 const head=new Element('head'),body=new Element('body'),footer=new Element('footer'),location=new URL(url);location.reload=()=>location.reloaded=true;
 const document={currentScript:{src:'https://rivfree.test/project/consent.js'},documentElement:{lang:'es',hasAttribute:()=>false},head,body,cookie:'',title:'RivFree',readyState:'complete',createElement:t=>new Element(t),getElementById:()=>null,querySelector:()=>footer};
 const window={RIVFREE_TRACKING:{ga4Id:'G-DQ9ZN0E47C',clarityId:'test123',cloudflareToken:'c7ffd1476a25414983f7c03faf7e0ace'},addEventListener:(k,f)=>events[k]=f,dispatchEvent:()=>{}};
 vm.runInNewContext(code,{window,document,location,URL,URLSearchParams,Date,Event:class{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:f=>f()});
 return {window,head,els,storage,location,events,click:text=>els.find(e=>e.textContent===text&&e.onclick).onclick()};
}
test('no collection before consent or after rejection, including a return visit',()=>{const t=setup();assert.equal(t.head.children.length,0);t.click('Rechazar');assert.equal(t.head.children.length,0);assert.equal(t.window.RivFreeConsent.allowed(),false);assert.equal(setup(undefined,t.storage.get('rivfree-cookie-choice-v4')).head.children.length,0)});
test('explicit acceptance starts the configured services once with advertising denied',()=>{const t=setup();t.click('Aceptar análisis');assert.equal(t.head.children.length,3);assert(t.head.children.some(s=>s.src==='https://www.googletagmanager.com/gtag/js?id=G-DQ9ZN0E47C'));assert(t.window.dataLayer.some(a=>a[0]==='consent'&&a[1]==='default'&&a[2].ad_storage==='denied'));assert(t.window.clarity.q.some(a=>a[0]==='consentv2'&&a[1].analytics_Storage==='granted'&&a[1].ad_Storage==='denied'));t.click('Aceptar análisis');assert.equal(t.head.children.length,3)});
test('withdrawal stores denial, disables GA and reloads to stop already loaded SDKs',()=>{const t=setup();t.click('Aceptar análisis');t.click('Rechazar');assert(t.window['ga-disable-G-DQ9ZN0E47C']);assert(t.location.reloaded);assert.equal(JSON.parse(t.storage.get('rivfree-cookie-choice-v4')).choice,'rejected')});
test('local and Studio views never load external trackers',()=>{const t=setup('http://127.0.0.1:8881/');t.click('Aceptar análisis');assert.equal(t.head.children.length,0);const p=setup('https://rivfree.test/?studio-preview=1');assert.equal(p.window.RivFreeConsent,undefined);assert.equal(p.head.children.length,0)});
test('invalid decisions do not start analytics; cross-tab withdrawal stops it',()=>{for(const saved of ['bad',JSON.stringify({choice:'accepted',version:1,providers:'wrong',expires:Date.now()+100000})])assert.equal(setup(undefined,saved).head.children.length,0);const t=setup();t.click('Aceptar análisis');t.events.storage({key:'rivfree-cookie-choice-v4',newValue:null});assert(t.location.reloaded)});
test('all entry pages use gated scripts; editable documents fetch fresh content',()=>{for(const file of ['index.html','privacy.html','cookies.html','terms.html']){const s=fs.readFileSync(file,'utf8');assert(!s.includes('script type="module" src="https://static.cloudflareinsights'));assert(s.includes('consent.js'));assert(s.includes('tracking-config.js'))}for(const file of ['privacidad','cookies','terminos'])assert(fs.readFileSync('politicas/'+file+'.txt','utf8').includes('=== PT ==='));assert(fs.readFileSync('legal.js','utf8').includes("cache:'no-store'"))});
